<?php
//USER
date_default_timezone_set('America/Los_Angeles');
//Check out this page for the most appropriate string https://www.php.net/manual/en/timezones.php

//PROVIDE FILE PATH FOR WHERE YOU WANT TO LOG

//VIDEO CONFIG VARIABLES
//  //PROVIDE FILE PATH FOR WHERE YOU WANT TO WRITE ALL VIDEO CONFIG OUTPUT FILES
$VIDEO_CONFIG_LOG_DIRECTORY = "/Volumes/BRAVO/WORKSPACE/DMZ/LOGS";

//VIDEO SEARCH VARIABLES
//  //PROVIDE FILE PATH FOR WHERE YOU WANT TO SEARCH
$VIDEO_SEARCH_DIRECTORY = "/Volumes/BRAVO/WORKSPACE/DMZ/STUFF";

//  //VIDEO SEARCH OUTPUT FILENAMES
//  //THIS FILE WILL CONTAIN ALL FILES FOUND
$VIDEO_SEARCH_LOG_FILE = "File_List.txt";
//  //
$VIDEO_SEARCH_FORMAT_FILE = "Formats_List.csv";
//  //
$VIDEO_SEARCH_SKIPPED_FILE = "Skipped_List.txt";

//  //MAYBE DON'T MESS WITH THIS ONE, YOU COULD BREAK THINGS
$VIDEO_SEARCH_FIND_PARAMETERS = "-type d -path '*/\.*' -prune -o -not -name '.*' -type f -print";

?>
